---
- name: Make sure HAProxy is installed.
  package: name=haproxy state=present

- name: Copy HAProxy configuration file.
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: 0644
    validate: haproxy -f %s -c -q
  notify: restart haproxy

- name: To make it started and enabled on boot.
  service: name=haproxy state=started enabled=yes

